# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1364ccb02deeaf62fa1b9ead5dda69ae85aea8875b2e854b072b141675591d1089769fab2653050e1bf3de1e10dc66d140e86c62a3926c245d56197887a937a

test:
  secret_key_base: 8c5e304b1d5364f67a45a12e27c6de10ba0416497b4cc1821eb38fe30409128a7276c1537413286bc065485f8f6fc0c1aa8e28f4c350d12b273795bb928f9567

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
